name = "rapid-vimnote"
main = "src/worker.js"
compatibility_date = "2026-05-04"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/s/*"]

[[d1_databases]]
binding = "DB"
database_name = "rapid-vimnote"
database_id = "51c03513-1255-4d1c-99ff-65f559ccb7a9"
